### ISSUE TITLE
Where is the code?

### ISSUE THREAD

**Issue by dawsongzhao0523** [xlang-ai/xlang#2]

**Comment by M1n9X** [comment]
The repository seems inactive, and there has been no response on Discord either.

**Comment by BlankCheng** [comment]
Thanks for your comments, and sorry for the late reply. We've been discussing our release plan and further todo items for the past few days. Here is a brief of our plan and motivations:
1. Refactoring and cleaning code first: since it is now a rather big project integrating toolkits, backend, and frontend, we hope the released version can be a somewhat organized and easy-to-contribute structure.
2. We have come up with some interesting and useful stuff to add to the package to benefit researchers and developers.
3. Demo updates: bug fixing and potential new features

We genuinely appreciate all the interest in implementing these usable agents, and that's why we built this project at the very beginning. Thus, we will definitely push toward the release plan.  It is estimated to take 3-4 weeks to refactor and add new features.  Our commitment is to provide clarity on the implementation details of our agents.

Though we can't guarantee the exact release date, we will try to answer every single question about our agent implementations and demos on github issues (kindly see #3), discord, and slack (again, sorry for the delayed reply).  In addition, if certain independent components of the code are ready before others, we will release them in sequence.
